import assert from 'node:assert/strict';
import { RequestState, StaleResponseError } from '../src/requestState.ts';
const state = new RequestState('home-a');
state.setProject('home-a', 3);
const snapshot = state.capture();
state.assertCurrent(snapshot);
const events = [];
state.subscribe(operation => events.push(operation));
const release = state.begin('Committing');
assert.equal(state.busy(), true);
assert.throws(() => state.begin('Deleting'), /Another operation/);
release(); release();
assert.deepEqual(events, [null, 'Committing', null]);
assert.equal(state.busy(), false);
state.setProject('home-a', 4);
assert.throws(() => state.assertCurrent(snapshot), StaleResponseError);
assert.throws(() => state.assertCurrent(snapshot, 3), StaleResponseError);
state.assertCurrent(snapshot, 4);
state.assertCurrent(snapshot, 5);
const sameHome = state.capture();
state.setProject('home-b', 0);
assert.throws(() => state.assertCurrent(sameHome, 100), StaleResponseError);
state.setProject('home-a', 4);
assert.throws(() => state.assertCurrent(sameHome, 4), StaleResponseError);
console.log('Request contracts passed: exclusive operations, release/retry, stale revision rejection, home epochs and returning-home races.');
