/** Run after npm run build, with backend deps on TIMBERBIM_TEST_PYTHON. */
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { createServer } from 'node:net';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
import {checkGuidedForms} from './guidedForms.mjs';
import {checkNavigation} from './navigation.mjs';
import {checkRendering} from './rendering.mjs';
import {checkAccessibility} from './accessibility.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const runtime = await mkdtemp(join(tmpdir(), 'timberbim-browser-'));
const reservation = createServer();
reservation.listen(0, '127.0.0.1');
await once(reservation, 'listening');
const port = reservation.address().port;
await new Promise(resolve => reservation.close(resolve));
const service = spawn(process.env.TIMBERBIM_TEST_PYTHON ?? 'python3', [
  '-m', 'uvicorn', 'server:app', '--host', '127.0.0.1', '--port', String(port), '--log-level', 'error',
], { cwd: join(root, 'backend'), env: { ...process.env, TIMBERBIM_DB_PATH: join(runtime, 'model.db') }, stdio: ['ignore', 'pipe', 'pipe'] });
let logs = '';
service.stderr.on('data', data => logs += data);
const url = `http://127.0.0.1:${port}`;
let browser;
function sameCamera(actual,expected){
  assert.equal(actual.projection,expected.projection);
  for(const key of ['position','target','up'])actual[key].forEach((n,i)=>assert.ok(Math.abs(n-expected[key][i])<1e-6,`camera ${key}[${i}]`));
  for(const key of ['near','far','zoom','ortho_height'])assert.ok(Math.abs(actual[key]-expected[key])<1e-6,`camera ${key}`);
}
async function pinSidebar(page,pinned){
  const button=page.getByRole('button',{name:pinned?'Pin sidebar':'Unpin sidebar',exact:true});
  if(await button.count())await button.click();
}
try {
  let ready = false;
  for (let i = 0; i < 100; i++) {
    if (service.exitCode !== null) throw new Error(`Backend exited: ${logs}`);
    try { ready = (await fetch(`${url}/api/health`)).ok; } catch {}
    if (ready) break;
    await new Promise(resolve => setTimeout(resolve, 100));
  }
  assert.ok(ready, `Backend did not start: ${logs}`);
  browser = await chromium.launch({
    executablePath: process.env.TIMBERBIM_TEST_BROWSER || undefined,
    headless: true, args: ['--no-sandbox'],
  });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  if(process.env.TIMBERBIM_TEST_ACCESSIBILITY_ONLY==='1'){
    await page.goto(url);await page.locator('#home-status').filter({hasText:'revision'}).waitFor();
    await checkAccessibility(browser,url,'default',errors);assert.deepEqual(errors,[]);
  }else if(process.env.TIMBERBIM_TEST_RENDERING_ONLY==='1'){
    await page.goto(url);await page.locator('#home-status').filter({hasText:'revision'}).waitFor();
    await checkRendering(browser,url,'default',errors);assert.deepEqual(errors,[]);
  }else if(process.env.TIMBERBIM_TEST_NAVIGATION_ONLY==='1'){
    await page.goto(url);await page.locator('#home-status').filter({hasText:'revision'}).waitFor();
    await checkNavigation(browser,url,errors);assert.deepEqual(errors,[]);
  }else if(process.env.TIMBERBIM_TEST_FORMS_ONLY==='1'){
    await page.goto(url);await page.locator('#home-status').filter({hasText:'revision'}).waitFor();
    await checkGuidedForms(browser,url,'default',errors);assert.deepEqual(errors,[]);
  }else{
  await page.addInitScript(() => {
    localStorage.setItem('timberbim.priceOverrides', '{bad');
    localStorage.setItem('timberbim.manualWallDraft.default', '{bad');
    localStorage.setItem('timberbim.manualTrussDraft.default', 'null');
    if(!localStorage.getItem('timberbim.view.v1.default'))localStorage.setItem('timberbim.view.v1.default','{bad');
  });
  await page.goto(url);
  await page.locator('#stats').filter({ hasText: 'timber members' }).waitFor();
  const viewRecovery=page.waitForEvent('download');
  await page.getByRole('button',{name:'Download saved view',exact:true}).click();
  assert.equal(await readFile(await (await viewRecovery).path(),'utf8'),'{bad');
  await page.getByRole('button',{name:'Discard saved view',exact:true}).click();
  assert.equal(await page.locator('#view-storage-status').textContent(),'');
  await page.getByRole('button', { name: 'Pin sidebar', exact: true }).click();
  assert.ok((await page.locator('#wall-draft-status').textContent()).includes('saved data is available for recovery'));
  await page.getByRole('button', { name: 'Manual Wall Frame Input', exact: true }).click();
  const savedDraft = page.waitForEvent('download');
  await page.locator('#wall-draft-status').getByRole('button', { name: 'Download saved draft', exact: true }).click();
  const recoveredDraft = await savedDraft;
  assert.equal(await readFile(await recoveredDraft.path(), 'utf8'), '{bad');
  await page.locator('#wall-draft-status').getByRole('button', { name: 'Discard saved draft', exact: true }).click();
  assert.equal(await page.locator('#wall-draft-status').textContent(), '');
  await page.getByRole('button', { name: 'Imports / Drawing Plans', exact: true }).click();
  const csv = 'type,level,segment_id,label,start_x_mm,start_z_mm,end_x_mm,end_z_mm,height_mm\nwall,1,W1,Test wall,0,0,0,0,2535\n';
  await page.locator('#csv-file').setInputFiles({ name: 'review.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) });
  await page.locator('#csv-summary').filter({ hasText: '1 errors' }).waitFor();
  assert.ok(await page.locator('#csv-commit').isDisabled());
  assert.ok(await page.locator('#csv-preview').isDisabled());
  await page.locator('#csv-table [data-field="end_x_mm"]').fill('3600');
  await page.locator('#csv-review').click();
  await page.locator('#csv-summary').filter({ hasText: '0 errors' }).waitFor();
  assert.ok(await page.locator('#csv-commit').isDisabled());
  await page.locator('#csv-preview').click();
  await page.waitForFunction(() => !document.querySelector('#csv-commit').disabled);
  await page.locator('#csv-table [data-field="label"]').fill('Changed after preview');
  assert.ok(await page.locator('#csv-commit').isDisabled());
  assert.ok(await page.locator('#preview-cancel').isHidden());
  await page.locator('#csv-review').click();
  await page.locator('#csv-summary').filter({ hasText: '0 errors' }).waitFor();
  await page.locator('#csv-preview').click();
  await page.waitForFunction(() => !document.querySelector('#csv-commit').disabled);
  await page.locator('#csv-commit').click();
  await page.locator('#csv-summary').filter({ hasText: 'Committed import batch' }).waitFor();
  assert.ok(await page.locator('#csv-commit').isDisabled());
  const beforeCsvEdit = await (await fetch(`${url}/api/model`)).json();
  const csvBatch = beforeCsvEdit.elements.find(member => member.source === 'csv_import').source_id;
  await page.locator(`[data-edit-batch="${csvBatch}"]`).click();
  await page.locator('#csv-summary').filter({ hasText: '0 errors' }).waitFor();
  assert.ok(await page.locator('#csv-mode').isDisabled());
  await page.locator('#csv-table [data-field="end_x_mm"]').fill('4200');
  await page.locator('#csv-review').click();
  await page.locator('#csv-summary').filter({ hasText: '0 errors' }).waitFor();
  await page.locator('#csv-preview').click();
  await page.waitForFunction(() => !document.querySelector('#csv-commit').disabled);
  await page.locator('#csv-commit').click();
  await page.locator('#csv-summary').filter({ hasText: 'Updated import batch' }).waitFor();
  const afterCsvEdit = await (await fetch(`${url}/api/model`)).json();
  assert.deepEqual(afterCsvEdit.elements.filter(member => member.source_id !== csvBatch), beforeCsvEdit.elements.filter(member => member.source_id !== csvBatch));
  assert.equal((await (await fetch(`${url}/api/import/batches`)).json()).batches.length, 1);
  await page.locator('#csv-edit-exit').click();
  const model = await (await fetch(`${url}/api/model`)).json();
  assert.ok(model.elements.some(element => element.segment_label === 'Changed after preview'));
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForFunction(() => document.querySelector('#viewport').clientWidth === 390
    && document.querySelector('canvas').getBoundingClientRect().width === 390
    && document.querySelector('#sidebar').getBoundingClientRect().width <= 390);
  const layout = await page.evaluate(() => ({
    viewport: document.querySelector('#viewport').clientWidth,
    sidebar: document.querySelector('#sidebar').getBoundingClientRect().width,
  }));
  assert.equal(layout.viewport, 390);
  assert.ok(layout.sidebar <= 390);
  const sheet=await page.locator('.sidebar-content').boundingBox();
  assert.ok(sheet.y>=844*.44&&sheet.height<=844*.56,'open drawer leaves the upper model usable');
  await page.getByRole('button',{name:'Close panel',exact:true}).click();
  assert.ok(await page.locator('.sidebar-content').isHidden());
  assert.ok(await page.getByRole('button',{name:'Plan',exact:true}).isVisible());
  await page.getByRole('button',{name:'Plan',exact:true}).click();
  assert.equal(await page.locator('#viewport').evaluate(el=>JSON.parse(el.dataset.camera).projection),'orthographic');
  await page.getByRole('button',{name:'Pin sidebar',exact:true}).click();
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('button', { name: 'Pricing', exact: true }).click();
  let releaseOlderBom;
  const olderBomGate = new Promise(resolve => releaseOlderBom = resolve);
  let markOlderBom;
  const olderBomCaptured = new Promise(resolve => markOlderBom = resolve);
  await page.route('**/api/bom.json?*', async route => {
    const response = await route.fetch();
    const body = await response.body();
    assert.ok(JSON.parse(body).rows.length > 0);
    markOlderBom();
    await olderBomGate;
    await route.fulfill({ response, body });
  }, { times: 1 });
  await page.locator('.price-override[data-key="sg8"]').fill('99');
  await page.locator('#pricing-save').click();
  await page.locator('#pricing-feedback').filter({ hasText: 'Project prices saved' }).waitFor();
  await olderBomCaptured;
  await page.locator('#pricing-expand').click();
  await page.locator('#pricing-workspace').waitFor();
  assert.ok(await page.locator('#pricing-table').getByRole('columnheader', { name: 'Currency / FX' }).isVisible());
  await page.getByRole('button', { name: 'Close Pricing', exact: true }).click();
  const priced = await (await fetch(`${url}/api/model`)).json();
  assert.ok(priced.meta.cost_summary.grand_total_usd > model.meta.cost_summary.grand_total_usd);
  assert.equal(priced.elements.find(element => element.material === 'SG8').unit_price_usd_per_lm, 99);
  await page.getByRole('button', { name: 'Settings / Warnings', exact: true }).click();
  await page.locator('#project-name').fill('Browser custom home');
  await page.locator('#project-create').click();
  await page.locator('#project-feedback').filter({ hasText: 'Opened Browser custom home' }).waitFor();
  const projectId = new URL(page.url()).searchParams.get('project_id');
  assert.match(projectId, /^[a-f0-9]{32}$/);
  const custom = await (await fetch(`${url}/api/model?project_id=${projectId}`)).json();
  assert.equal(custom.elements.length, 0);
  await page.locator('#bom-summary').filter({ hasText: '0 of 0 rows' }).waitFor({ state: 'attached' });
  releaseOlderBom();
  await page.waitForFunction(() => document.querySelector('#bom-summary').textContent.includes('0 of 0 rows'));
  console.log('Request race checked: an old home BOM response cannot overwrite the newly opened home.');
  await page.getByRole('button', { name: 'Manual Wall Frame Input', exact: true }).click();
  await page.locator('#wall-form [name="segment_label"]').fill('<b id="injected-label">Literal label</b>');
  const wallDraft = await page.evaluate(projectId => JSON.parse(localStorage.getItem(`timberbim.manualWallDraft.${projectId}`)), projectId);
  assert.equal(wallDraft.schema_version, 2);
  assert.equal(wallDraft.project_id, projectId);
  assert.equal(wallDraft.fields.segment_label, '<b id="injected-label">Literal label</b>');
  let releasePreview;
  const previewGate = new Promise(resolve => releasePreview = resolve);
  await page.route('**/api/manual/wall-frame/preview?*', async route => {
    await previewGate; await route.continue();
  }, { times: 1 });
  await page.locator('#wall-preview').click();
  await page.locator('#workspace-request-status').filter({ hasText: 'Preparing preview' }).waitFor();
  assert.ok(await page.locator('#project-select').isDisabled());
  assert.ok(await page.locator('#pricing-save').isDisabled());
  assert.ok(await page.locator('#truss-preview').isDisabled());
  releasePreview();
  await page.locator('#wall-result').filter({ hasText: 'Preview:' }).waitFor();
  await page.locator('#wall-form [name="end_x_mm"]').fill('5700');
  assert.ok(await page.locator('#wall-commit').isDisabled());
  assert.ok(await page.locator('#preview-cancel').isHidden());
  await page.locator('#wall-preview').click();
  await page.waitForFunction(() => !document.querySelector('#wall-commit').disabled);
  let releaseCancelledPreview;
  const cancelledPreviewGate = new Promise(resolve => releaseCancelledPreview = resolve);
  await page.route('**/api/manual/wall-frame/preview?*', async route => {
    await cancelledPreviewGate;
    await route.continue().catch(() => {}); // The browser may already have aborted it.
  }, { times: 1 });
  await page.locator('#wall-preview').click();
  await page.locator('#workspace-request-status').filter({ hasText: 'Preparing preview' }).waitFor();
  await page.locator('#preview-cancel').click();
  await page.waitForFunction(() => document.querySelector('#workspace-request-status').textContent === '');
  assert.ok(await page.locator('#wall-commit').isDisabled());
  assert.ok(await page.locator('#preview-cancel').isHidden());
  releaseCancelledPreview();
  await page.locator('#wall-preview').click();
  await page.waitForFunction(() => !document.querySelector('#wall-commit').disabled);
  await page.locator('#wall-commit').click();
  await page.locator('#wall-result').filter({ hasText: 'Committed wall' }).waitFor();
  assert.ok(await page.locator('#wall-commit').isDisabled());
  const firstWall = await (await fetch(`${url}/api/model?project_id=${projectId}`)).json();
  const wallAssembly = firstWall.elements[0].source_id;
  await page.getByRole('button', { name: 'Imports / Drawing Plans', exact: true }).click();
  await page.locator(`[data-edit-batch="${wallAssembly}"]`).click();
  await page.locator('#wall-edit-status').filter({ hasText: 'Editing saved wall' }).waitFor();
  await page.locator('#wall-form [name="end_x_mm"]').fill('5100');
  await page.locator('#wall-preview').click();
  await page.waitForFunction(() => !document.querySelector('#wall-commit').disabled);
  assert.equal(await page.locator('.model-tree-item').filter({ hasText: 'manual_wall' }).count(), 0);
  await page.locator('#wall-commit').click();
  await page.locator('#wall-result').filter({ hasText: 'Updated wall' }).waitFor();
  await page.locator('#wall-form [name="end_x_mm"]').fill('5400');
  await page.reload();
  await page.locator('#wall-edit-status').filter({ hasText: 'Editing saved wall' }).waitFor();
  assert.equal(await page.locator('#wall-form [name="end_x_mm"]').inputValue(), '5400');
  assert.ok(await page.locator('#wall-commit').isDisabled());
  await page.locator('#wall-preview').click();
  await page.waitForFunction(() => !document.querySelector('#wall-commit').disabled);
  await page.locator('#wall-commit').click();
  await page.locator('#wall-result').filter({ hasText: 'Updated wall' }).waitFor();
  const savedWall = await (await fetch(`${url}/api/model?project_id=${projectId}`)).json();
  assert.deepEqual([...new Set(savedWall.elements.map(member => member.source_id))], [wallAssembly]);
  await page.locator('#wall-edit-exit').click();
  assert.equal(await page.locator('#wall-form [name="end_x_mm"]').inputValue(), '5700');
  const withWall = await (await fetch(`${url}/api/model?project_id=${projectId}`)).json();
  assert.ok(withWall.elements.length > 0);
  assert.ok(withWall.elements.every(element => element.source === 'manual_wall'));
  await page.getByRole('button', { name: 'Building Specs', exact: true }).click();
  await page.locator('#roof [data-r="hip"]').click();
  await page.waitForFunction(async ({ url, projectId, revision }) => {
    const model = await (await fetch(`${url}/api/model?project_id=${projectId}`)).json();
    return model.meta.project.revision > revision && model.meta.roof === 'hip';
  }, { url, projectId, revision: withWall.meta.project.revision });
  await page.reload();
  await page.locator('#stats').filter({ hasText: 'timber members' }).waitFor();
  const reopened = await (await fetch(`${url}/api/model?project_id=${projectId}`)).json();
  assert.deepEqual(reopened.elements, withWall.elements);
  assert.equal(new URL(page.url()).searchParams.get('section'), 'specs');
  await page.getByRole('button', { name: 'Unpin sidebar', exact: true }).click();
  await page.getByRole('button', { name: 'Model browser', exact: true }).click();
  await page.locator('#model-search').fill('Literal label');
  await page.locator('.model-tree-item').first().click();
  await page.locator('#member-inspector').waitFor();
  assert.ok((await page.locator('#member-details').textContent()).includes('<b id="injected-label">Literal label</b>'));
  assert.equal(await page.locator('#injected-label').count(), 0);
  await page.getByRole('button', { name: 'Isolate selection', exact: true }).click();
  await page.getByRole('button', { name: 'Show all', exact: true }).click();
  await page.getByRole('button', { name: 'Plan', exact: true }).click();
  await page.getByRole('button', { name: 'Fit model', exact: true }).click();
  await page.getByRole('button', { name: 'Manual Truss Input', exact: true }).click();
  await page.locator('#truss-form [name="truss_type"]').selectOption('custom');
  await page.locator('#truss-form [name="nodes_csv"]').fill('id,x,y\nL,-4500,0\nA,0,2100\nR,4500,0\nB,0,0');
  await page.locator('#truss-form [name="members_csv"]').fill('start_node,end_node,element_type,size,material\nL,A,top_chord,140x45,SG8\nA,R,top_chord,140x45,SG8\nL,R,bottom_chord,90x45,SG8\nB,A,king_post,90x45,SG8');
  await page.locator('#truss-form [name="quantity"]').fill('2');
  await page.locator('#truss-preview').click();
  await page.locator('#truss-result').filter({ hasText: 'Preview: 2 trusses' }).waitFor();
  await page.locator('#truss-commit').click();
  await page.locator('#truss-result').filter({ hasText: 'Committed truss layout' }).waitFor();
  assert.ok(await page.locator('#truss-commit').isDisabled());
  const withTrusses = await (await fetch(`${url}/api/model?project_id=${projectId}`)).json();
  const trusses = withTrusses.elements.filter(member => member.source === 'manual_truss');
  assert.equal(new Set(trusses.map(member => member.truss_id)).size, 2);
  assert.equal(new Set(trusses.map(member => member.instance_id)).size, 2);
  assert.ok(trusses.some(member => member.member_role === 'king_post'));
  assert.ok(trusses.every(member => member.start_node && member.end_node && member.engineering_status === 'unchecked'));
  assert.equal(new Set(trusses.map(member => member.physical_member_id)).size, 8);
  assert.ok(trusses.filter(member => member.member_role === 'bottom_chord').every(member => member.cut_length_mm === 9000));
  const trussAssembly = trusses[0].source_id;
  await page.getByRole('button', { name: 'Imports / Drawing Plans', exact: true }).click();
  await page.locator(`[data-edit-batch="${trussAssembly}"]`).click();
  await page.locator('#truss-edit-status').filter({ hasText: 'Editing saved truss layout' }).waitFor();
  await page.locator('#truss-form [name="quantity"]').fill('3');
  await page.locator('#truss-preview').click();
  await page.waitForFunction(() => !document.querySelector('#truss-commit').disabled);
  await page.locator('#truss-commit').click();
  await page.locator('#truss-result').filter({ hasText: 'Updated truss layout' }).waitFor();
  const editedTrusses = (await (await fetch(`${url}/api/model?project_id=${projectId}`)).json()).elements.filter(member => member.source === 'manual_truss');
  assert.equal(new Set(editedTrusses.map(member => member.instance_id)).size, 3);
  assert.deepEqual([...new Set(editedTrusses.map(member => member.source_id))], [trussAssembly]);
  await page.locator('#truss-edit-exit').click();
  await page.locator('#truss-form [name="nodes_csv"]').fill('id,x,y\nBAD,NaN,0');
  await page.locator('#truss-preview').click();
  await page.locator('#truss-result').filter({ hasText: 'finite numbers' }).waitFor();
  await page.getByRole('button', { name: 'Manual Wall Frame Input', exact: true }).click();
  await page.locator('#wall-form [name="stud_material"]').selectOption('SG10');
  await page.locator('#wall-form [name="stud_size"]').fill('240x90');
  await page.locator('#wall-preview').click();
  await page.locator('#wall-result').filter({ hasText: 'unpriced cuts' }).waitFor();
  await page.locator('#wall-commit').click();
  await page.locator('#wall-result').filter({ hasText: 'Committed wall' }).waitFor();
  await page.locator('#home-status').filter({ hasText: 'unpriced boards' }).waitFor();
  assert.ok((await page.locator('#stats').textContent()).includes('unpriced boards'));
  await page.getByRole('button', { name: 'BOM', exact: true }).click();
  await page.locator('#bom-summary').filter({ hasText: 'boards' }).waitFor();
  await page.locator('#bom-expand').click();
  await page.locator('#bom-workspace').waitFor();
  assert.ok((await page.locator('#bom-workspace').boundingBox()).width > 1000);
  await page.locator('#bom-search').fill('Truss bottom chord');
  await page.locator('#bom-summary').filter({ hasText: '1 of' }).waitFor();
  const chord = await page.locator('#bom-table tbody tr').textContent();
  assert.ok(chord.includes('special order'));
  await page.locator('#bom-search').fill('');
  await page.locator('#bom-price').selectOption('unpriced');
  await page.locator('#bom-table tbody tr.unpriced').first().waitFor();
  assert.ok((await page.locator('#bom-table').textContent()).includes('Unpriced'));
  await page.locator('#bom-sort').selectOption('qty');
  await page.locator('#bom-workspace summary').click();
  await page.locator('[data-bom-column="date"]').check();
  assert.ok(await page.locator('#bom-table').getByRole('columnheader', { name: 'Source date' }).isVisible());
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok((await page.locator('#bom-workspace').boundingBox()).width <= 390);
  await page.keyboard.press('Escape');
  assert.ok(await page.locator('#bom-workspace').isHidden());
  await page.waitForFunction(() => document.activeElement?.id === 'bom-expand');
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.reload();
  await page.locator('#home-status').filter({ hasText: 'Browser custom home' }).waitFor();
  await page.getByRole('button', { name: 'Manual Truss Input', exact: true }).click();
  assert.equal(await page.locator('#truss-form [name="nodes_csv"]').inputValue(), 'id,x,y\nBAD,NaN,0');
  assert.ok(await page.locator('#truss-commit').isDisabled());
  const blockedContext = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  await blockedContext.addInitScript(() => {
    Object.defineProperty(window, 'localStorage', { get() { throw new DOMException('Storage denied', 'SecurityError'); } });
  });
  const blockedPage = await blockedContext.newPage();
  blockedPage.on('pageerror', error => errors.push(error.message));
  await blockedPage.goto(`${url}/?project_id=${projectId}`);
  await blockedPage.locator('#home-status').filter({ hasText: 'Browser custom home' }).waitFor();
  await blockedPage.getByRole('button', { name: 'Pin sidebar', exact: true }).click();
  await blockedPage.getByRole('button', { name: 'Manual Wall Frame Input', exact: true }).click();
  await blockedPage.locator('#wall-form [name="segment_label"]').fill('Storage unavailable');
  await blockedPage.locator('#wall-draft-status').filter({ hasText: 'Browser storage is unavailable' }).waitFor();
  await blockedContext.close();
  const beforeCreation = await (await fetch(`${url}/api/model?project_id=${projectId}`)).json();
  const homeCount = (await (await fetch(`${url}/api/projects`)).json()).projects.length;
  await page.getByRole('button', { name: 'Settings / Warnings', exact: true }).click();
  await page.locator('#project-name').fill('Retry sample creation');
  await page.locator('#project-mode').selectOption('sample');
  let abortedCreation = false;
  await page.route('**/api/projects?*', async route => {
    if (route.request().method() === 'POST' && !abortedCreation) {
      abortedCreation = true;
      await route.fetch();
      await route.abort('failed'); // Lose the reply after the server created the home.
    } else await route.continue();
  });
  await page.locator('#project-create').click();
  await page.locator('#project-feedback').filter({ hasText: 'Failed to fetch' }).waitFor();
  await page.locator('#project-create').click();
  await page.locator('#project-feedback').filter({ hasText: 'Opened Retry sample creation' }).waitFor();
  const createdId = new URL(page.url()).searchParams.get('project_id');
  assert.notEqual(createdId, projectId);
  const createdHome = await (await fetch(`${url}/api/model?project_id=${createdId}`)).json();
  assert.equal(createdHome.meta.project.geometry_mode, 'sample');
  assert.ok(createdHome.elements.length > 0);
  assert.equal((await (await fetch(`${url}/api/projects`)).json()).projects.length, homeCount+1);
  assert.deepEqual(await (await fetch(`${url}/api/model?project_id=${projectId}`)).json(), beforeCreation);
  await page.unroute('**/api/projects?*');
  await page.getByRole('button', { name: 'Imports / Drawing Plans', exact: true }).click();
  await page.locator('#home-example').selectOption('rectangle');
  await page.locator('#home-definition-status').filter({ hasText: 'Definition loaded' }).waitFor();
  await page.locator('#home-preview').click();
  await page.waitForFunction(() => !document.querySelector('#home-save').disabled);
  const savedBeforeHome = await (await fetch(`${url}/api/model?project_id=${createdId}`)).json();
  const homePreview = await page.locator('#model-browser-list button').count();
  assert.ok(homePreview > 0);
  page.once('dialog', dialog => dialog.accept());
  await page.locator('#home-save').click();
  await page.locator('#home-definition-status').filter({ hasText: 'Home saved' }).waitFor();
  const rectangle = await (await fetch(`${url}/api/model?project_id=${createdId}`)).json();
  assert.equal(rectangle.meta.project.geometry_mode, 'custom');
  assert.ok(rectangle.elements.some(e => e.type_code === 'truss_web'));
  assert.ok(!rectangle.elements.some(e => e.type_code === 'rafter' || e.type_code === 'ceiling_joist'));
  assert.ok(rectangle.elements.length < savedBeforeHome.elements.length);
  const exportEvent = page.waitForEvent('download');
  await page.locator('#home-export').click();
  const homeDownload = await exportEvent;
  const archiveText = await readFile(await homeDownload.path(), 'utf8');
  assert.equal(JSON.parse(archiveText).archive_schema_version, 1);
  await page.locator('#home-example').selectOption('two_level');
  await page.locator('#home-definition-status').filter({ hasText: 'Definition loaded' }).waitFor();
  await page.locator('#home-preview').click();
  await page.waitForFunction(() => !document.querySelector('#home-save').disabled);
  await page.locator('#preview-cancel').click();
  assert.ok(await page.locator('#home-save').isDisabled());
  await page.locator('#home-preview').click();
  await page.waitForFunction(() => !document.querySelector('#home-save').disabled);
  page.once('dialog', dialog => dialog.accept());
  await page.locator('#home-save').click();
  await page.locator('#home-definition-status').filter({ hasText: 'Home saved' }).waitFor();
  await page.reload();
  await page.locator('#home-status').filter({ hasText: 'Two-level home' }).waitFor();
  await page.getByRole('button', { name: 'Imports / Drawing Plans', exact: true }).click();
  await page.locator('#home-file').setInputFiles({ name: 'portable-home.json', mimeType: 'application/json', buffer: Buffer.from(archiveText) });
  await page.locator('#home-definition-status').filter({ hasText: 'Definition loaded' }).waitFor();
  assert.ok(await page.locator('#home-preserve').isDisabled());
  await page.locator('#home-preview').click();
  await page.waitForFunction(() => !document.querySelector('#home-save').disabled);
  page.once('dialog', dialog => dialog.accept());
  await page.locator('#home-save').click();
  await page.locator('#home-definition-status').filter({ hasText: 'Home saved' }).waitFor();
  const archiveRestored = await (await fetch(`${url}/api/model?project_id=${createdId}`)).json();
  assert.equal(archiveRestored.elements.length, rectangle.elements.length);
  assert.equal(archiveRestored.meta.cost_summary.grand_total_usd, rectangle.meta.cost_summary.grand_total_usd);
  assert.equal(archiveRestored.meta.review.profile.structural_approval, false);
  assert.ok(archiveRestored.meta.review.checks.some(c => c.code === 'truss.topology' && c.status === 'evaluated_within_assumptions'));
  await page.getByRole('button', { name: 'Settings / Warnings', exact: true }).click();
  await page.locator('#rule-review').filter({ hasText: 'not independently verified' }).waitFor();
  await page.locator('#settings-warnings [data-warning-member]').first().click();
  await page.locator('#member-inspector').waitFor({ state: 'visible' });
  assert.ok((await page.locator('#member-details').textContent()).includes('Structural capacity and connections remain unchecked'));
  await pinSidebar(page,false);
  await page.getByRole('button',{name:'Clear selection',exact:true}).click();
  await page.locator('#view-options summary').click();
  await page.locator('#view-dimensions').check();
  assert.equal(await page.locator('.dimension-label').count(),3);
  assert.ok((await page.locator('.dimension-label').first().textContent()).includes('extent'));
  await page.locator('#view-section').check();
  await page.locator('#section-keep').selectOption('upper');
  await page.locator('#section-position').fill('4500');await page.locator('#section-position').press('Tab');
  await page.getByRole('button',{name:'Plan',exact:true}).click();
  const clippedCamera=await page.locator('#viewport').evaluate(el=>JSON.parse(el.dataset.camera));
  assert.equal(clippedCamera.projection,'orthographic');assert.ok(clippedCamera.target[0]>4.5,'fit follows the retained east portion');
  assert.deepEqual(clippedCamera.up,[0,0,-1]);
  await page.screenshot({path:'/tmp/lite-bim-section-review.png'});
  await page.getByRole('button',{name:'Building Specs',exact:true}).click();
  await page.locator('#source-filter').selectOption('generated');
  await page.locator('#layers [data-c="roof"]').uncheck();
  await page.locator('#view-level').selectOption('1');
  await page.waitForFunction(({home})=>{
    const saved=JSON.parse(localStorage.getItem(`timberbim.view.v1.${home}`));
    return saved?.view.section?.position_mm===4500&&saved.view.dimensions&&saved.view.source==='generated'&&saved.view.level===1&&saved.view.layers.roof===false;
  },{home:createdId});
  await page.reload();await page.locator('#home-status').filter({hasText:'Rectangle home'}).waitFor();
  await page.locator('#view-options summary').click();
  assert.equal(await page.locator('#section-position').inputValue(),'4500');assert.ok(await page.locator('#view-dimensions').isChecked());
  sameCamera(await page.locator('#viewport').evaluate(el=>JSON.parse(el.dataset.camera)),clippedCamera);
  // Preview filters/cameras remain temporary; cancel restores all committed view hints.
  await pinSidebar(page,true);
  await page.getByRole('button',{name:'Imports / Drawing Plans',exact:true}).click();
  await page.locator('#home-example').selectOption('two_level');
  await page.locator('#home-definition-status').filter({hasText:'Definition loaded'}).waitFor();
  await page.locator('#home-preview').click();await page.waitForFunction(()=>!document.querySelector('#home-save').disabled);
  assert.ok(!(await page.locator('#view-section').isChecked()));
  assert.equal(await page.locator('#source-filter').inputValue(),'');assert.equal(await page.locator('#view-level').inputValue(),'');
  await page.getByRole('button',{name:'Front',exact:true}).click();
  await page.locator('#preview-cancel').click();
  assert.ok(await page.locator('#view-section').isChecked());
  sameCamera(await page.locator('#viewport').evaluate(el=>JSON.parse(el.dataset.camera)),clippedCamera);
  assert.equal(await page.locator('#source-filter').inputValue(),'generated');assert.equal(await page.locator('#view-level').inputValue(),'1');
  assert.ok(!(await page.locator('#layers [data-c="roof"]').isChecked()));
  assert.ok(await page.locator('#home-save').isDisabled());
  await page.getByRole('button',{name:'Settings / Warnings',exact:true}).click();
  await page.locator('#project-select').selectOption(projectId);
  await page.locator('#home-status').filter({hasText:'Browser custom'}).waitFor();
  assert.ok(!(await page.locator('#view-section').isChecked()));
  await page.locator('#project-select').selectOption(createdId);
  await page.locator('#home-status').filter({hasText:'Rectangle home'}).waitFor();
  assert.ok(await page.locator('#view-section').isChecked());
  // A warning reveals its member even when the current section excludes it.
  await page.locator('#settings-warnings [data-warning-member]').first().click();
  await page.locator('#member-inspector').waitFor();assert.ok(!(await page.locator('#view-section').isChecked()));
  await pinSidebar(page,false);
  await page.getByRole('button',{name:'Model browser',exact:true}).click();
  await page.locator('#model-search').fill('generated');
  await page.locator('.model-tree-item').first().focus();await page.keyboard.press('Enter');
  await page.getByRole('button',{name:'Fit selection',exact:true}).press('Enter');
  assert.ok(await page.getByRole('button',{name:'Fit selection',exact:true}).evaluate(el=>document.activeElement===el));
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'Manual Wall Frame Input',exact:true}).click();
  await page.getByRole('button',{name:'Close panel',exact:true}).click();
  assert.ok(await page.locator('.sidebar-content').isHidden());
  assert.ok(await page.getByRole('button',{name:'Plan',exact:true}).isVisible());
  await page.getByRole('button',{name:'Manual Wall Frame Input',exact:true}).click();
  await page.locator('#add-opening').click();
  await page.locator('#wall-preview').click();
  await page.locator('#draft-dimensions').filter({hasText:'Preview wall intent: span 6000.0 mm'}).waitFor();
  assert.ok((await page.locator('#draft-dimensions').textContent()).includes('width 1200 mm'));
  assert.ok((await page.locator('#draft-dimensions').textContent()).includes('head 2100 mm'));
  await page.locator('#preview-cancel').click();assert.equal(await page.locator('#draft-dimensions').textContent(),'');
  await page.getByRole('button',{name:'Close panel',exact:true}).click();
  await checkGuidedForms(browser,url,createdId,errors);
  await checkNavigation(browser,url,errors);
  await checkRendering(browser,url,createdId,errors);
  await checkAccessibility(browser,url,createdId,errors);
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: home-local view/camera recovery, orthographic/clipped dimensions, preview restoration, keyboard/mobile bottom sheet, applicability, reusable homes/webs/archives, editing/pricing, drafts and request races/retry.');
  }
} catch (error) {
  console.error('Backend output:', logs);
  if (browser) {
    for (const context of browser.contexts()) for (const page of context.pages()) {
    for (const selector of ['#home-definition-status', '#csv-summary', '#wall-result', '#truss-result', '#project-feedback', '#pricing-feedback'])
      console.error(selector, await page.locator(selector).textContent().catch(() => 'unavailable'));
    }
  }
  throw error;
} finally {
  if (browser) await browser.close();
  if (service.exitCode === null) {
    service.kill('SIGTERM');
    await once(service, 'exit');
  }
  await rm(runtime, { recursive: true, force: true });
}
